__package__ = 'mtag_tool'
__description__ = 'MP3 tag编辑器，支持从网易云补全歌曲信息.'
__url__ = 'https://github.com/wang0618/mtag_tool'
__version__ = "1.0.0"
__version_info__ = (1, 0, 0, 0)
__author__ = 'WangWeimin'
__author_email__ = 'wang0.618@qq.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2021 WangWeimin'
